import type { Proveedor } from "./tipos";
export const proveedoresIniciales: Proveedor[] = [
  {
    idProveedor: 1,
    nitRuc: "20601234567",
    razonSocial: "Pedrauser",
    direccion: "Av. Landaeta, Sepa dios donde vive",
    telefono: "+591 77756186",
    correo: "pedrauser@sonic.com",
    estado: "Activo",
    puntajeDesempeno: 95,
    ordenesCompra: 48,
    montoTotalComprado: 125000,
    descuentoVolumen: [
      { cantidadMinima: 50, descuento: 5 },
      { cantidadMinima: 100, descuento: 8 },
      { cantidadMinima: 500, descuento: 12 },
    ],
    tiempoPromedioDias: 1.5,
    documentos: [
      {
        idDocumento: 101,
        tipoDocumento: "Ficha RUC",
        numeroDocumento: "20601234567",
        fechaVencimiento: "2027-12-31",
        archivo: "ficha_ruc_2026.pdf",
        estadoValidacion: "Válido",
      },
      {
        idDocumento: 102,
        tipoDocumento: "Certificado de Homologación",
        numeroDocumento: "CH-2025-089",
        fechaVencimiento: "2026-11-15",
        archivo: "homologacion_cert.pdf",
        estadoValidacion: "Válido",
      },
    ],
    catalogoProductos: [
      {
        idProducto: 1,
        sku: "PROD-LOG-001",
        nombre: "Caja de Cartón Corrugado Doble Canal (50x40x40)",
        categoria: "Empaque y Embalaje",
        descripcion:
          "Caja de alta resistencia para transporte pesado e importaciones.",
        precioPactado: 4.5,
        tiempoEntregaEstimado: "24 a 48 horas",
        stockDisponible: 5000,
        unidadMedida: "Unidad",
      },
      {
        idProducto: 2,
        sku: "PROD-LOG-002",
        nombre: "Cinta Embalaje Transparente (Pack x 6)",
        categoria: "Empaque y Embalaje",
        descripcion: "Adhesivo de acrílico de alta fijación industrial.",
        precioPactado: 18.2,
        tiempoEntregaEstimado: "24 horas",
        stockDisponible: 1200,
        unidadMedida: "Pack",
      },
      {
        idProducto: 3,
        sku: "PROD-LOG-003",
        nombre: "Film Stretch Strechable Industrial 20 micras",
        categoria: "Paletizado",
        descripcion:
          "Rollo de plástico film transparente para asegurar parihuelas.",
        precioPactado: 32.0,
        tiempoEntregaEstimado: "2 a 3 días hábiles",
        stockDisponible: 850,
        unidadMedida: "Rollo",
      },
    ],
  },
  {
    idProveedor: 2,
    nitRuc: "20109876543",
    razonSocial: "Ya no se qeu poner wazaaa",
    direccion: "Calle Comercio, casco viejo creo",
    telefono: "+591 23462742",
    correo: "cambien@losdatos.com",
    estado: "Observado",
    puntajeDesempeno: 72,
    ordenesCompra: 24,
    montoTotalComprado: 58000,
    descuentoVolumen: [
      { cantidadMinima: 50, descuento: 4 },
      { cantidadMinima: 100, descuento: 7 },
      { cantidadMinima: 500, descuento: 10 },
    ],
    tiempoPromedioDias: 3.2,
    documentos: [
      {
        idDocumento: 103,
        tipoDocumento: "Ficha RUC",
        numeroDocumento: "20109876543",
        fechaVencimiento: "2026-05-10",
        archivo: "ficha_ruc_dist.pdf",
        estadoValidacion: "Vencido",
      },
    ],
    catalogoProductos: [
      {
        idProducto: 8,
        sku: "PROD-LOG-001",
        nombre: "Caja de Cartón Corrugado Doble Canal (50x40x40)",
        categoria: "Empaque y Embalaje",
        descripcion:
          "Caja de alta resistencia para transporte pesado e importaciones.",
        precioPactado: 4.1,
        tiempoEntregaEstimado: "48 a 72 horas",
        stockDisponible: 3000,
        unidadMedida: "Unidad",
      },
      {
        idProducto: 4,
        sku: "PROD-NOR-101",
        nombre: "Aceite Lubricante Multipropósito 1L",
        categoria: "Mantenimiento",
        descripcion:
          "Formulación para engranajes y maquinaria industrial pesada.",
        precioPactado: 28.5,
        tiempoEntregaEstimado: "3 a 5 días hábiles",
        stockDisponible: 340,
        unidadMedida: "Litro",
      },
      {
        idProducto: 5,
        sku: "PROD-NOR-102",
        nombre: "Guantes de Nitrilo Industrial Reforzado (Caja x 100)",
        categoria: "EPP y Seguridad",
        descripcion: "Protección para manejo de químicos y grasas.",
        precioPactado: 45.0,
        tiempoEntregaEstimado: "2 a 4 días hábiles",
        stockDisponible: 600,
        unidadMedida: "Caja",
      },
    ],
  },
  {
    idProveedor: 3,
    nitRuc: "20554433221",
    razonSocial: "Nilmar ponte a trabajar",
    direccion: "Senkata, El alto",
    telefono: "+591 70544491",
    correo: "natesito@waza.com",
    estado: "Inactivo",
    puntajeDesempeno: 45,
    ordenesCompra: 8,
    montoTotalComprado: 14200,
    descuentoVolumen: [
      { cantidadMinima: 50, descuento: 3 },
      { cantidadMinima: 100, descuento: 6 },
      { cantidadMinima: 500, descuento: 9 },
    ],
    tiempoPromedioDias: 5.0,
    documentos: [],
    catalogoProductos: [],
  },
  {
    idProveedor: 4,
    nitRuc: "20448899112",
    razonSocial: "Campielcampi",
    direccion: "nosexdd, la paz",
    telefono: "+591 71994068",
    correo: "samiel@elcmampi.com",
    estado: "Activo",
    puntajeDesempeno: 88,
    ordenesCompra: 36,
    montoTotalComprado: 94000,
    descuentoVolumen: [
      { cantidadMinima: 50, descuento: 5 },
      { cantidadMinima: 100, descuento: 9 },
      { cantidadMinima: 500, descuento: 13 },
    ],
    tiempoPromedioDias: 1.8,
    documentos: [
      {
        idDocumento: 104,
        tipoDocumento: "Ficha RUC",
        numeroDocumento: "20448899112",
        fechaVencimiento: "2027-08-20",
        archivo: "ficha_ruc_tecno.pdf",
        estadoValidacion: "Válido",
      },
    ],
    catalogoProductos: [
      {
        idProducto: 6,
        sku: "PROD-TEC-501",
        nombre: "Lector de Código de Barras Láser USB / Bluetooth",
        categoria: "Hardware Almacén",
        descripcion:
          "Escáner industrial con soporte ergonómico y lectura 2D/QR.",
        precioPactado: 185.0,
        tiempoEntregaEstimado: "24 a 48 horas",
        stockDisponible: 120,
        unidadMedida: "Unidad",
      },
      {
        idProducto: 7,
        sku: "PROD-TEC-502",
        nombre: "Impresora Térmica de Etiquetas Adhesivas",
        categoria: "Hardware Almacén",
        descripcion: "Resolución 203 DPI, velocidad de impresión 152 mm/s.",
        precioPactado: 640.0,
        tiempoEntregaEstimado: "2 días hábiles",
        stockDisponible: 45,
        unidadMedida: "Unidad",
      },
    ],
  },
];
export const datosFrecuenciaMensual = [
  { mes: "Abr", ordenes: 12, monto: 22000 },
  { mes: "May", ordenes: 18, monto: 34000 },
  { mes: "Jun", ordenes: 15, monto: 28000 },
  { mes: "Jul", ordenes: 22, monto: 45000 },
  { mes: "Ago", ordenes: 28, monto: 56000 },
  { mes: "Sep", ordenes: 21, monto: 41000 },
];
